// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application'

import AlertController from './alert_controller'
application.register('alert', AlertController)

import AppointmentDateController from './appointment_date_controller'
application.register('appointment-date', AppointmentDateController)

import AutocompleteController from './autocomplete_controller'
application.register('autocomplete', AutocompleteController)

import CollapseController from './collapse_controller'
application.register('collapse', CollapseController)

import ConditionalFieldController from './conditional_field_controller'
application.register('conditional-field', ConditionalFieldController)

import ConfirmItemAccessoriesController from './confirm_item_accessories_controller'
application.register(
  'confirm-item-accessories',
  ConfirmItemAccessoriesController
)

import DynamicFieldsController from './dynamic_fields_controller'
application.register('dynamic-fields', DynamicFieldsController)

import EmailSettingsEditorController from './email_settings_editor_controller'
application.register('email-settings-editor', EmailSettingsEditorController)

import FindToolController from './find_tool_controller'
application.register('find-tool', FindToolController)

import HoldOrderController from './hold_order_controller'
application.register('hold-order', HoldOrderController)

import ImageEditorController from './image_editor_controller'
application.register('image-editor', ImageEditorController)

import ItemFilterController from './item_filter_controller'
application.register('item-filter', ItemFilterController)

import ModalController from './modal_controller'
application.register('modal', ModalController)

import MultiSelectController from './multi_select_controller'
application.register('multi-select', MultiSelectController)

import NotesController from './notes_controller'
application.register('notes', NotesController)

import ReservationDatesController from './reservation_dates_controller'
application.register('reservation-dates', ReservationDatesController)

import SidebarController from './sidebar_controller'
application.register('sidebar', SidebarController)

import StripeController from './stripe_controller'
application.register('stripe', StripeController)

import TagEditorController from './tag_editor_controller'
application.register('tag-editor', TagEditorController)

import ToggleController from './toggle_controller'
application.register('toggle', ToggleController)

import TreeNavController from './tree_nav_controller'
application.register('tree-nav', TreeNavController)
