---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require: []
domains: []
plugins:
- solargraph-standardrb
reporters:
- require_not_found
- standardrb
require_paths: []
max_files: 5000
