blank_issues_enabled: false
contact_links:
  - name: Bug report
    about: 🔨What needs fixing? ✨
    url: https://github.com/rubyforgood/circulate/issues/new?template=custom_bug_report.md&projects=rubyforgood/circulate/4
  - name: 💡Feature request
    about: 🔨What needs building? ✨
    url: https://github.com/rubyforgood/circulate/issues/new?template=feature_request.md&projects=rubyforgood/circulate/4
