default: &defaults
  push_api_key: "<%= ENV["APPSIGNAL_PUSH_API_KEY"] %>"
  name: "Circulate"
  request_headers:
    - HTTP_ACCEPT
    - HTTP_ACCEPT_CHARSET
    - HTTP_ACCEPT_ENCODING
    - HTTP_ACCEPT_LANGUAGE
    - HTTP_CACHE_CONTROL
    - HTTP_CONNECTION
    - CONTENT_LENGTH
    - PATH_INFO
    - HTTP_RANGE
    - REQUEST_METHOD
    - REQUEST_PATH
    - SERVER_NAME
    - SERVER_PORT
    - SERVER_PROTOCOL
    # The above are the default. The following is to help us narrow down if
    # only certain clients are encountering InvalidAuthenticityToken errors.
    - HTTP_USER_AGENT
    - HTTP_REFERER

  # Errors that should not be recorded by AppSignal
  # For more information see our docs:
  # https://docs.appsignal.com/ruby/configuration/ignore-errors.html
  ignore_errors:
    # We do error page rendering via Rails config.exceptions_app, which means
    # that RecordNotFound exceptions coming from controller actions are ok.
    - ActiveRecord::RecordNotFound

  # See https://docs.appsignal.com/ruby/configuration/options.html for
  # all configuration options.

# Configuration per environment, leave out an environment or set active
# to false to not push metrics for that environment.
development:
  <<: *defaults
  active: false

staging:
  <<: *defaults
  active: true

production:
  <<: *defaults
  active: true
