module AppointmentsHelper
  def format_appointment_times(start, stop)
    date_format = "%l:%M%P"
    "#{start.strftime(date_format).strip} - #{stop.strftime(date_format).strip}"
  end

  def appointment_time(appointment)
    format_appointment_times(appointment.starts_at, appointment.ends_at)
  end

  # The sort key generated by this metnod is used to keep the appointments
  # on the appointments index in order as they are moved between lists.
  def appointment_sort_key(appointment)
    start_time = appointment.starts_at.hour
    member_name = preferred_or_default_name(appointment.member)
    created_at = appointment.created_at.to_i
    "#{start_time}-#{member_name}-#{created_at}"
  end
end
