name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

env:
  RAILS_ENV: test
  CI: "true"
  RUBYOPT: "-W0"
  SECRET_KEY_BASE: "secret_key_base"
  PARALLEL_WORKERS: 1

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        test: [test]
        include:
          - test: test
            command: test

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_HOST: localhost
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bin/rails assets:precompile

      - name: Setup database
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          bundle exec rake db:test:prepare

      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres
          PGPORT: ${{ job.services.postgres.ports[5432] }}
        run: |
          date
          bundle exec rails test test/models/loan_test.rb:83

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   if: ${{ matrix.test == 'system' && failure() }}

      - uses: actions/upload-artifact@v3
        if: ${{ matrix.test == 'system' && failure() }}
        with:
          path: |
            tmp/screenshots
            test/reports
            log/test.log
